Maxarre/HippoWeb

app/controllers/consultations_controller.rb, app/controllers/doctors_controller.rb, config/routes.rb
=> controller consultation et doctor

app/controllers/patients_controller.rb, app/views/patients/new.html.erb, config/routes.rb, db/migrate/20190603160235_create_patients.rb, db/schema.rb
=> NewPatient

app/controllers/patients_controller.rb, app/views/patients/new.html.erb
=> Patient new

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/controllers/patients_controller.rb, app/models/patient.rb, app/views/patients/insurance.html.erb, app/views/patients/medicalrecord.html.erb, app/views/patients/new.html.erb, app/views/patients/treatments.html.erb, app/views/users/dashboard.html.erb, config/routes.rb
=> new pages for form

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_searchbar.scss, app/assets/stylesheets/components/_sidebar.scss, app/controllers/users_controller.rb, app/models/patient.rb, app/models/user.rb, app/views/shared/_card_meeting.html.erb, app/views/users/dashboard.html.erb
=> new setups

app/assets/stylesheets/components/_cards.scss, app/views/shared/_card_meeting.html.erb
=> card meeting

app/assets/stylesheets/components/_card.scss, app/views/patients/insurance.html.erb, app/views/patients/medicalrecord.html.erb, app/views/patients/treatments.html.erb
=> new patient pages

app/javascript/packs/application.js, app/javascript/plugins/flatpickr.js, app/views/patients/new.html.erb, package.json, yarn.lock
=> datepicker and placeholders

app/assets/stylesheets/components/_card.scss, app/views/patients/insurance.html.erb, app/views/patients/medicalrecord.html.erb, app/views/patients/treatments.html.erb
=> NewCorrect

app/controllers/consultations_controller.rb, app/javascript/plugins/flatpickr.js, app/views/shared/_form_consultation_new.html.erb, config/routes.rb
=> NewMeeting

app/assets/stylesheets/components/_cards.scss, app/controllers/consultations_controller.rb, app/controllers/patients_controller.rb, app/views/patients/show.html.erb, app/views/shared/_card_consultation.html.erb
=> consultation card in patient show

app/controllers/emails_controller.rb, app/models/email.rb, app/views/emails/create.html.erb, app/views/emails/index.html.erb, app/views/emails/new.html.erb, app/views/users/dashboard.html.erb, config/routes.rb, db/migrate/20190606095535_create_emails.rb, db/schema.rb, test/controllers/emails_controller_test.rb, test/models/email_test.rb
=> email-controller

app/controllers/patients_controller.rb, app/views/patients/index.html.erb, db/seeds.rb
=> seeds working

app/controllers/consultations_controller.rb, app/views/consultations/new.html.erb
=> Search Patient

app/assets/stylesheets/components/_cards.scss, app/controllers/emails_controller.rb, app/models/patient.rb, app/views/emails/index.html.erb, config/routes.rb, db/migrate/20190607085652_add_dates_to_emails.rb, db/schema.rb
=> email-history

app/views/users/dashboard.html.erb, config/untitled.rb, db/seeds.rb
=> ordered-calendar

app/controllers/consultations_controller.rb, app/views/patients/show.html.erb
=> last follow up

app/controllers/consultations_controller.rb, db/seeds.rb
=> this is the real 'follow-up edit'

app/models/consultation.rb, db/seeds.rb
=> tiiiiiiiiiiime

db/migrate/20190603160311_create_consultations.rb, db/schema.rb, db/seeds.rb
C'EST LA MEEEEEEEEEEEEEEEEEEEEEEEERDE!!!!!!!!!!!!!!!!!!!!!!!!!!
=> MotherFNdb

db/migrate/20190603160311_create_consultations.rb, db/schema.rb, db/seeds.rb
=> Revert "MotherFNdb"

db/migrate/20190603160311_create_consultations.rb, db/schema.rb, db/seeds.rb
=> Revert "Revert "MotherFNdb""

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_patient_index.scss, app/views/emails/index.html.erb, app/views/users/dashboard.html.erb
=> Revert "MERCIGERMAINLEMAGICIEN"

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_patient_index.scss, app/views/emails/index.html.erb, app/views/users/dashboard.html.erb
=> Revert "Revert "MERCIGERMAINLEMAGICIEN""

app/views/patients/_show.html.erb
=> SearchPatient

app/controllers/consultations_controller.rb, app/javascript/components/remove_tag.js, app/javascript/packs/application.js, app/views/consultations/add_tags.js.erb, app/views/consultations/edit.html.erb, app/views/consultations/remove_tags.js.erb, app/views/shared/_tagglist.html.erb, config/routes.rb
=> fucking tags

app/assets/stylesheets/pages/_home.scss, app/views/devise/sessions/new.html.erb, db/seeds.rb
=> log-in & seed

app/controllers/consultations_controller.rb, app/views/consultations/edit.html.erb, db/consultation_templates.yml, db/seeds.rb
=> yaml-tag-v1

app/assets/stylesheets/pages/_home.scss, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/emails/create.html.erb, app/views/emails/new.html.erb
=> values and color log-in

app/assets/stylesheets/components/_dashboard.scss, app/assets/stylesheets/pages/_home.scss, app/views/users/dashboard.html.erb
=> modifviews

app/controllers/consultations_controller.rb, app/controllers/emails_controller.rb, app/views/consultations/_edit.html.erb, app/views/consultations/edit.js.erb, app/views/emails/_new.html.erb, app/views/emails/new.js.erb, app/views/patients/_show.html.erb, app/views/patients/show.html.erb, config/routes.rb
=> Ajax Martin

app/controllers/consultations_controller.rb, app/javascript/plugins/tag.js, app/views/consultations/add_tags.js.erb, app/views/consultations/edit.html.erb, app/views/shared/_taginput.html.erb, db/consultation_templates.yml, db/seeds.rb
=> Modif views

app/assets/stylesheets/pages/_home.scss, db/seeds.rb
=> seedscolors

app/views/patients/show.html.erb
=> not showing empty

app/views/consultations/new.html.erb, app/views/patients/_show.html.erb, app/views/patients/show.html.erb, app/views/shared/_taginput.html.erb, app/views/users/dashboard.html.erb
=> empty-date

app/javascript/plugins/flatpickr.js, app/views/consultations/new.html.erb
=> new empty dates

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_dashboard.scss, app/assets/stylesheets/components/_tags.scss, app/assets/stylesheets/components/_text_responsivity.scss, app/views/patients/_show.html.erb, app/views/shared/_tagglist.html.erb, app/views/users/dashboard.html.erb
=> Revert "lapin"
